version: '3'

services:
  db:
    container_name: springboot_react_db
    image: postgres
    volumes:
      - springboot_react_db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGPORT=5433
    ports:
      - "5433:5433"
    restart: on-failure
    
  api:
    build: ./backend
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
    springboot_react_db: {}
